name: Terraform apply

on:
  workflow_run:
    workflows: ["Terraform plan"]
    types:
      - completed

env:  
  AWS_REGION: ap-south-1


jobs:
  apply:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0

      - name: Terraform Init
        working-directory: "terraform"
        run: terraform init

      - name: Terraform Init
        working-directory: "stickynotes-app"
        run: terraform init

      - name: Terraform Plan
        working-directory: "terraform"
        run: terraform plan

      - name: Terraform Plan
        working-directory: "stickynotes-app"
        run: terraform plan     


      - name: Terraform Apply
        working-directory: "terraform "     
        run: terraform apply -auto-approve


      - name: Terraform Apply
        working-directory: "terraform"
        run: terraform apply -auto-approve
        